# Generated by Django 5.0.4 on 2024-04-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='project',
            new_name='project_id',
        ),
    ]
