# Generated by Django 5.0.4 on 2024-04-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_value_rate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='project',
            new_name='project_id',
        ),
    ]
