# Generated by Django 5.0.4 on 2024-04-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_commentreports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreports',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.CreateModel(
            name='ProjectReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
