# Generated by Django 5.0.4 on 2024-04-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_comment_id_commentreports_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreports',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
