# Generated by Django 5.0.4 on 2024-04-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_comment_commentreports_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreport',
            name='project',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
        migrations.DeleteModel(
            name='ProjectReport',
        ),
    ]
