# Generated by Django 5.0.4 on 2024-04-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_category_project_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
