# Generated by Django 5.0.4 on 2024-04-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
