# Generated by Django 5.0.4 on 2024-04-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/img'),
        ),
    ]
